### ISSUE TITLE
Proximity and ALS aren't working on the 520

### ISSUE THREAD

**Issue by TBM13** [Android4Lumia/android_kernel_nokia_msm8x27#16]
The ALS only reports zero, and the proximity sensor goes from 1.5 cm to 2 cm if i push the touchscreen at the top.

A few people have already confirmed that these sensors don't work on their Lumia 520.

The 525 doesn't seems to be affected by this issue. I'm not sure about other devices.

**Comment by feherneoh** [comment]
No idea who and when broke these, as they worked just fine on my 520 before

**Comment by TBM13** [comment]
Update: 
This doesn't seems to be a kernel issue.

I'm going to close this one and open another one in the fame device tree repository.
